### ISSUE TITLE
Segfault with such test

### ISSUE THREAD

**Issue by VasiliyMatr** [ILAB-2ndYEAR/T02TREE#12]
https://github.com/ILAB-2ndYEAR/T02TREE/blob/fbc061ea4d45af564acb74ba45c99931a98ef32a/tests/insert-test1#L1-L2

@TheRedHotHabanero

**Comment by Tako-San** [comment]
@VasiliyMatr could you provide the reason of segfault?

**Comment by VasiliyMatr** [comment]
I don't know. I was just testing erase method.

**Comment by TheRedHotHabanero** [comment]
fixed
