### ISSUE TITLE
DFS

### ISSUE THREAD

**Issue by TheRedHotHabanero** [ILAB-2ndYEAR/T02TREE#14]
fix DFS @VasiliyMatr

**Comment by Tako-San** [comment]
> fix DFS @VasiliyMatr 

You may assign him for this issue

**Comment by VasiliyMatr** [comment]
So poor description, please provide more info. There is no sense is such issues otherwise.

**Comment by Tako-San** [comment]
> So poor description, please provide more info. There is no sense is such issues otherwise.

Read issue #13, and make DFS independent from outer functor

**Comment by VasiliyMatr** [comment]
These issues are not connected.

**Comment by Tako-San** [comment]
> These issues are not connected.

Anyway, fix it
