### ISSUE TITLE
Possible nullptr access attempts here.

### ISSUE THREAD

**Issue by VasiliyMatr** [ILAB-2ndYEAR/T02TREE#2]
https://github.com/ILAB-2ndYEAR/T02TREE/blob/9b7e99227c6d1ab8bfa6b45395cbdeefafd50ca4/headers/tree-impl.hh#L49-L80

**Comment by VasiliyMatr** [comment]
Add assertions if there is no correct usage case with nullptr fields.

**Comment by VasiliyMatr** [comment]
@TheRedHotHabanero

**Comment by TheRedHotHabanero** [comment]
fixed
