### ISSUE TITLE
Redundant &&

### ISSUE THREAD

**Issue by derzhavin3016** [ILAB-2ndYEAR/T02TREE#22]
https://github.com/ILAB-2ndYEAR/T02TREE/blob/2749dee8f7a2c17be181e2b0c4ba3d364c11c19a/headers/tree-impl.hh#L324
Why don't you use constant ref here?

**Comment by derzhavin3016** [comment]
Also, I don't think that "tester" is an appropriate name for this parameter, because DFS may be used for different purposes, not only tests

**Comment by VasiliyMatr** [comment]
https://github.com/ILAB-2ndYEAR/T02TREE/blob/2749dee8f7a2c17be181e2b0c4ba3d364c11c19a/headers/tree-impl.hh#L324

We don't use constant ref here because operator() is not const method in some cases.
