### ISSUE TITLE
Uninitialized variables

### ISSUE THREAD

**Issue by VasiliyMatr** [ILAB-2ndYEAR/T02TREE#3]
https://github.com/ILAB-2ndYEAR/T02TREE/blob/9b7e99227c6d1ab8bfa6b45395cbdeefafd50ca4/headers/tree-impl.hh#L231-L233

**Comment by VasiliyMatr** [comment]
@TheRedHotHabanero

**Comment by TheRedHotHabanero** [comment]
fixed
