### ISSUE TITLE
Useless else

### ISSUE THREAD

**Issue by Tako-San** [ILAB-2ndYEAR/T02TREE#4]
https://github.com/ILAB-2ndYEAR/T02TREE/blob/master/headers/tree-impl.hh#L220-L222
Are you sure that it is necessary?

**Comment by VasiliyMatr** [comment]
@Tako-San, whut?
![image](https://user-images.githubusercontent.com/70326825/142554033-b5761c8c-95c1-4883-ab80-671ba99a0f31.png)

**Comment by Tako-San** [comment]
@VasiliyMatr, looks like problem has already been solved
