### ISSUE TITLE
Template parameters

### ISSUE THREAD

**Issue by Tako-San** [ILAB-2ndYEAR/T02TREE#5]
https://github.com/ILAB-2ndYEAR/T02TREE/blob/master/headers/tree-impl.hh#L45

Are your `Data` or `Compare` always classes? I think it is possible to use default types. So I think that `typename` is more appropriate word

**Comment by VasiliyMatr** [comment]
![image](https://user-images.githubusercontent.com/70326825/142553493-7906341a-0a79-4075-a983-7b29d654c1a6.png)

**Comment by VasiliyMatr** [comment]
I think that our version is viable.
