### ISSUE TITLE
Uninitialised variable

### ISSUE THREAD

**Issue by Tako-San** [ILAB-2ndYEAR/T02TREE#6]
https://github.com/ILAB-2ndYEAR/T02TREE/blob/master/headers/tree-impl.hh#L231-L233

Better assign `nullptr`

**Comment by VasiliyMatr** [comment]
@Tako-San, whut?
![image](https://user-images.githubusercontent.com/70326825/142554433-d726c377-6c8d-4cdf-96a5-0bc626916190.png)

**Comment by Tako-San** [comment]
@VasiliyMatr, looks like problem has already been solved
